
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const VERIFY = "Verify";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL= "LOGIN_FAIL";
export const GET_USER_DATA = "GET_USER_DATA";
export const FORGOT_PASSWORD  = "FORGOT_PASSWORD";
export const RESET_PASSWORD  = "RESET_PASSWORD";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const UPDATE_PROFILE_IMAGE = "UPDATE_PROFILE_IMAGE";
export const LOGOUT = "LOGOUT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT"
export const  RESET_PAGE = "RESET_PAGE"
export const API_ERROR = "API_ERROR";
export const SET_CONVERSATION = "SET_CONVERSATION";
