
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const RESEND_VERIFICATION_SUCCESS ="RESEND_VERIFICATION_SUCCESS"
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const LODING="LODING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const GET_USER_DATA = "GET_USER_DATA";
export const FORGOT_PASSWORD_SUCCESS  = "FORGOT_PASSWORD_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const UPDATE_PROFILE_IMAGE = "UPDATE_PROFILE_IMAGE";
export const LOGOUT = "LOGOUT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT"
export const RESET_PAGE = "RESET_PAGE"
export const API_ERROR = "API_ERROR";
export const SET_CONVERSATION = "SET_CONVERSATION";
