export const  SET_BOOTCAMPS_LOADER = 'SET_BOOTCAMPS_LOADER';
export const  FETCH_BOOTCAMPS = 'FETCH_BOOTCAMPS';
export const  FETCH_BOOTCAMP = 'FETCH_BOOTCAMP'
export const  RESET_BOOTCAMPS = 'RESET_BOOTCAMPS';
export const  SORT_BOOTCAMPS = 'SORT_BOOTCAMPS';
export const SEARCH_BOOTCAMPS = 'SEARCH_BOOTCAMPS'
export const TOGGLE_GROUP_FAVOURITE = 'TOGGLE_GROUP_FAVOURITE'