export const  SET_BOOTCAMPS_LOADER = 'SET_BOOTCAMPS_LOADER';
export const  FETCH_BOOTCAMPS_SUCCESS = 'FETCH_BOOTCAMPS_SUCCESS';
export const  RESET_BOOTCAMPS = 'RESET_BOOTCAMPS';
export const  SORT_BOOTCAMPS = 'SORT_BOOTCAMPS';