export const GET_CART_ITEMS = 'GET_CART_ITEMS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART ='REMOVE_FROM_CART'
export const CREATE_ORDER = 'CREATE_ORDER'
export const GET_ORDER_ITEMS = 'GET_ORDER_ITEMS'
export const LOADING = 'LOADING'
export const CHECKOUT = 'CHECKOUT'
export const API_ERROR = 'API_ERROR'
