export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA'
export const GET_UPDATED_PROFILE_DATA = 'GET_UPDATED_PROFILE_DATA';
export const FETCH_PROFILE_FAILED = 'FETCH_PROFILE_FAILED'